/*

 PT_PLACEHOLDER_CAST.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 46

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Cast_TilesBank 0

/* Super Gameboy palette 0 */
#define Cast_TilesSGBPal0c0 28638
#define Cast_TilesSGBPal0c1 13951
#define Cast_TilesSGBPal0c2 6169
#define Cast_TilesSGBPal0c3 5163

/* Super Gameboy palette 1 */
#define Cast_TilesSGBPal1c0 28638
#define Cast_TilesSGBPal1c1 8935
#define Cast_TilesSGBPal1c2 6596
#define Cast_TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Cast_TilesSGBPal2c0 28638
#define Cast_TilesSGBPal2c1 8935
#define Cast_TilesSGBPal2c2 6596
#define Cast_TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Cast_TilesSGBPal3c0 28638
#define Cast_TilesSGBPal3c1 8935
#define Cast_TilesSGBPal3c2 6596
#define Cast_TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Cast_TilesCGBPal0c0 6076
#define Cast_TilesCGBPal0c1 8935
#define Cast_TilesCGBPal0c2 6596
#define Cast_TilesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define Cast_TilesCGBPal1c0 6076
#define Cast_TilesCGBPal1c1 8935
#define Cast_TilesCGBPal1c2 6596
#define Cast_TilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define Cast_TilesCGBPal2c0 6076
#define Cast_TilesCGBPal2c1 8935
#define Cast_TilesCGBPal2c2 6596
#define Cast_TilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define Cast_TilesCGBPal3c0 6076
#define Cast_TilesCGBPal3c1 8935
#define Cast_TilesCGBPal3c2 6596
#define Cast_TilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define Cast_TilesCGBPal4c0 6076
#define Cast_TilesCGBPal4c1 8935
#define Cast_TilesCGBPal4c2 6596
#define Cast_TilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define Cast_TilesCGBPal5c0 6076
#define Cast_TilesCGBPal5c1 8935
#define Cast_TilesCGBPal5c2 6596
#define Cast_TilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define Cast_TilesCGBPal6c0 6076
#define Cast_TilesCGBPal6c1 8935
#define Cast_TilesCGBPal6c2 6596
#define Cast_TilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define Cast_TilesCGBPal7c0 6076
#define Cast_TilesCGBPal7c1 8935
#define Cast_TilesCGBPal7c2 6596
#define Cast_TilesCGBPal7c3 5344

/* SGB palette entries. */
#define Cast_TilesSGB0 0
#define Cast_TilesSGB1 0
#define Cast_TilesSGB2 0
#define Cast_TilesSGB3 0
#define Cast_TilesSGB4 0
#define Cast_TilesSGB5 0
#define Cast_TilesSGB6 0
#define Cast_TilesSGB7 0
#define Cast_TilesSGB8 0
#define Cast_TilesSGB9 0
#define Cast_TilesSGB10 0
#define Cast_TilesSGB11 0
#define Cast_TilesSGB12 0
#define Cast_TilesSGB13 0
#define Cast_TilesSGB14 0
#define Cast_TilesSGB15 0
#define Cast_TilesSGB16 0
#define Cast_TilesSGB17 0
#define Cast_TilesSGB18 0
#define Cast_TilesSGB19 0
#define Cast_TilesSGB20 0
#define Cast_TilesSGB21 0
#define Cast_TilesSGB22 0
#define Cast_TilesSGB23 0
#define Cast_TilesSGB24 0
#define Cast_TilesSGB25 0
#define Cast_TilesSGB26 0
#define Cast_TilesSGB27 0
#define Cast_TilesSGB28 0
#define Cast_TilesSGB29 0
#define Cast_TilesSGB30 0
#define Cast_TilesSGB31 0
#define Cast_TilesSGB32 0
#define Cast_TilesSGB33 0
#define Cast_TilesSGB34 0
#define Cast_TilesSGB35 0
#define Cast_TilesSGB36 0
#define Cast_TilesSGB37 0
#define Cast_TilesSGB38 0
#define Cast_TilesSGB39 0
#define Cast_TilesSGB40 0
#define Cast_TilesSGB41 0
#define Cast_TilesSGB42 0
#define Cast_TilesSGB43 0
#define Cast_TilesSGB44 0
#define Cast_TilesSGB45 0
#define Cast_TilesSGB46 0

/* CGB palette entries. */
#define Cast_TilesCGB0 0
#define Cast_TilesCGB1 0
#define Cast_TilesCGB2 0
#define Cast_TilesCGB3 0
#define Cast_TilesCGB4 0
#define Cast_TilesCGB5 0
#define Cast_TilesCGB6 0
#define Cast_TilesCGB7 0
#define Cast_TilesCGB8 0
#define Cast_TilesCGB9 0
#define Cast_TilesCGB10 0
#define Cast_TilesCGB11 0
#define Cast_TilesCGB12 0
#define Cast_TilesCGB13 0
#define Cast_TilesCGB14 0
#define Cast_TilesCGB15 0
#define Cast_TilesCGB16 0
#define Cast_TilesCGB17 0
#define Cast_TilesCGB18 0
#define Cast_TilesCGB19 0
#define Cast_TilesCGB20 0
#define Cast_TilesCGB21 0
#define Cast_TilesCGB22 0
#define Cast_TilesCGB23 0
#define Cast_TilesCGB24 0
#define Cast_TilesCGB25 0
#define Cast_TilesCGB26 0
#define Cast_TilesCGB27 0
#define Cast_TilesCGB28 0
#define Cast_TilesCGB29 0
#define Cast_TilesCGB30 0
#define Cast_TilesCGB31 0
#define Cast_TilesCGB32 0
#define Cast_TilesCGB33 0
#define Cast_TilesCGB34 0
#define Cast_TilesCGB35 0
#define Cast_TilesCGB36 0
#define Cast_TilesCGB37 0
#define Cast_TilesCGB38 0
#define Cast_TilesCGB39 0
#define Cast_TilesCGB40 0
#define Cast_TilesCGB41 0
#define Cast_TilesCGB42 0
#define Cast_TilesCGB43 0
#define Cast_TilesCGB44 0
#define Cast_TilesCGB45 0
#define Cast_TilesCGB46 0
/* Start of tile array. */
const extern unsigned char Cast_Tiles[];

/* End of PT_PLACEHOLDER_CAST.H */
