/*

 TEST_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\gbtd22\PrincessTomato_Bkg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Visual_MapWidth 20
#define Visual_MapHeight 18
#define Visual_MapBank 0

const extern unsigned char Visual_Map[];

/* End of TEST_MAP.H */
